apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-app-route
  namespace: webinar-wmops
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  to:
    kind: Service
    name: web-app-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  path: /
