apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: webinar-vm
  namespace: webinar-vmops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: webinar-vm-volume
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    name: cx1.large
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: webinar-vm
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              cdrom:
                bus: sata
              bootOrder: 2
          interfaces:
            - name: default
              masquerade: {}
            - name: nic204                 # ← ENTFERNEN, falls NAD nicht existiert
              model: virtio
              state: up
              bridge: {}
      networks:
        - name: default
          pod: {}
        - name: nic204                     # ← ENTFERNEN, falls NAD nicht existiert
          multus:
            networkName: default/nad204
      subdomain: headless
      # Healthchecks gegen den in-guest Webserver
      readinessProbe:
        httpGet:
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 6
      livenessProbe:
        httpGet:
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 90
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      volumes:
        - name: rootdisk
          dataVolume:
            name: webinar-vm-volume
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              user: artzoul
              password: redhat123
              write_files:
                - path: /opt/hello/index.html
                  permissions: '0644'
                  content: |
                    <!doctype html>
                    <html>
                      <head><meta charset="utf-8"><title>Hello</title></head>
                      <body style="font-family: system-ui, sans-serif; margin: 3rem;">
                        <h1>Hello from a VM on OpenShift 👋</h1>
                        <p>VS Code → GitHub → Argo CD → OpenShift</p>
                      </body>
                    </html>
                - path: /etc/systemd/system/hello-web.service
                  permissions: '0644'
                  content: |
                    [Unit]
                    Description=Simple Hello Web (python http.server)
                    After=network-online.target
                    Wants=network-online.target
                    [Service]
                    WorkingDirectory=/opt/hello
                    ExecStart=/usr/bin/python3 -m http.server 80
                    Restart=always
                    [Install]
                    WantedBy=multi-user.target
              runcmd:
                - mkdir -p /opt/hello
                - systemctl daemon-reload
                - systemctl enable --now hello-web.service
