apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: webinar-vm
  namespace: webinar-vmops
  annotations:
    description: Fedora Hello-World Demo VM
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: webinar-vm
    os.template.kubevirt.io/fedora: 'true'
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        app: webinar-vm
        kubevirt.io/domain: webinar-vm
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              cdrom:
                bus: sata
              bootOrder: 2
          interfaces:
            - name: default
              model: virtio
              masquerade: {}
          networkInterfaceMultiqueue: true
          rng: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: artzoul
              password: redhat123
              chpasswd: { expire: False }
              write_files:
                - path: /opt/hello/index.html
                  permissions: '0644'
                  content: |
                    <!doctype html>
                    <html>
                      <head><meta charset="utf-8"><title>Hello</title></head>
                      <body style="font-family: system-ui, sans-serif; margin: 3rem;">
                        <h1>This VM on OpenShift is alive, serving content, and doing its best… which is more than I can say for most humans before coffee. 🧪🛰️☕</h1>
                        <p>VS Code → GitHub → Argo CD → OpenShift</p>
                      </body>
                    </html>
                - path: /etc/systemd/system/hello-web.service
                  permissions: '0644'
                  content: |
                    [Unit]
                    Description=Simple Hello Web (python http.server)
                    After=network-online.target
                    Wants=network-online.target

                    [Service]
                    WorkingDirectory=/opt/hello
                    ExecStart=/usr/bin/python3 -m http.server 80
                    Restart=always

                    [Install]
                    WantedBy=multi-user.target
              runcmd:
                - mkdir -p /opt/hello
                - systemctl daemon-reload
                - systemctl enable --now hello-web.service
